### ISSUE TITLE
Build fails due to  'const class QStringRef' has no member named 'toInt'

### ISSUE THREAD

**Issue by ColumPaget** [psemiletov/eko#2]
Hi,

Build fails on my system with the error:

```
utils.cpp:101:25: error: 'const class QStringRef' has no member named 'toInt'
```

Looking in utils.cpp at line 101 I find the function:
```
size_t get_value_with_default (const QStringRef &val, size_t def)
{
  QString s = val.toString();
  if (! s.isEmpty())
    return (size_t) val.toInt();
  else
      return def;
}
```

I *think* that `return (size_t) val.toInt()` should be `return (size_t) s.toInt()`  Making this change allows building on my system.

regards

Colum

**Comment by psemiletov** [comment]
Thank you, all seems fixed now!
