### ISSUE TITLE
Link to AppImage download

### ISSUE THREAD

**Issue by probonopd** [psemiletov/eko#5]
Please upload the AppImage to GitHub Releases.

Reference:
https://github.com/AppImage/AppImageHub/issues/15

**Comment by Symbian9** [comment]
Build status badge
`[![Build status](https://travis-ci.org/psemiletov/eko.svg?branch=master)](https://travis-ci.org/psemiletov/eko)`
[![Build status](https://travis-ci.org/psemiletov/eko.svg?branch=master)](https://travis-ci.org/psemiletov/eko)

**Comment by psemiletov** [comment]
Yes, I'm trying to fix it...

**Comment by Symbian9** [comment]
Try setup `continuouse` using this additional script for `.travis.yml`
* https://github.com/probonopd/uploadtool

REFERENCE
* https://github.com/Symbian9/azpainter/issues/17

**Comment by psemiletov** [comment]
Fixed (https://transfer.sh/10eddD/EKO-git.2d7d959-x86_64.AppImage) and will be tagged soon.

**Comment by probonopd** [comment]
Is there any chance an AppImage would be available on https://github.com/psemiletov/eko/releases soon? Thanks.
